/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Natural History Museum of Los Angeles County (https://sketchfab.com/NHMLA)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-raccoon-procyon-lotor-0e494f866fc24ab3ae2d8fe02b1d6110
Title: Low poly raccoon (Procyon lotor)
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import scene from '../assets/3d/raccoon.glb'


// insert UCSD raccoon vid
// https://www.reddit.com/r/UCSD/comments/qxc16u/just_some_raccoons/

const Raccoon = ({ currentAnimation, ...props }) => {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(scene);
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        console.log(actions)

        Object.values(actions).forEach((action) => action.stop());

        if (actions[currentAnimation]) {
            actions[currentAnimation].play();
        }


    }, [actions, currentAnimation])

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model"
                    position={[4.408, 0, -4.693]}
                    rotation={[-Math.PI / 2, 0, Math.PI]}
                    scale={0.2}
                >
                    <group
                        name="ba6f0b178b3540b4beea76ec61331c8dfbx"
                        rotation={[Math.PI / 2, 0, 0]}
                    >
                        <group name="Object_2">
                            <group name="RootNode">
                                <group
                                    name="Racoon"
                                    rotation={[-Math.PI, Math.PI / 6, Math.PI]}
                                >
                                    <group name="Geometry">
                                        <group name="Raccoon" />
                                    </group>
                                    <group name="Main">
                                        <group name="DeformationSystem">
                                            <group name="Object_9">
                                                <primitive object={nodes._rootJoint} />
                                                <skinnedMesh
                                                    name="Object_12"
                                                    geometry={nodes.Object_12.geometry}
                                                    material={materials.Racoon}
                                                    skeleton={nodes.Object_12.skeleton}
                                                />
                                                <group
                                                    name="Object_11"
                                                    rotation={[-Math.PI, Math.PI / 6, Math.PI]}
                                                />
                                            </group>
                                        </group>
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

// useGLTF.preload("/raccoon.glb");

export default Raccoon;
